version: '3'

services:
  dbos:
    image: mysql:5.7
    volumes:
      - dbos_data_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootd
      MYSQL_USER: team
      MYSQL_PASSWORD: teams
      MYSQL_DTATABASE: mydb
    
  wordpressos:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on:
      - dbos
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: team
      WORDPRESS_DB_PASSWORD: teams
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wdp_storage_new:/var/ww/html
        
volumes:
   wdp_storage_new:
   dbos_data_new:
